### ISSUE TITLE
How to prevent Frame2seq from using cysteine?

### ISSUE THREAD

**Issue by caseysm** [dakpinaroglu/Frame2seq#1]
Hi,

This looks like it is going to be a wonderful tool for generating proteins. I was curious if there was a way to prevent the model from generating outputs that have cysteines in them?

Thanks!

**Comment by dakpinaroglu** [comment]
Hi,

You can now omit cysteines by designing with the following:

```
from frame2seq import Frame2seqRunner

runner = Frame2seqRunner()
runner.design(pdb_file, chain_id, temperature, num_samples, omit_AA=['C'])
```

Using the same format, you can omit any AA or a combination of AAs. See updated README for reference.

If installed via pip, upgrade to most recent Frame2seq using `pip install --upgrade frame2seq`
